const LogoPath = require("../assets/Logotype.jpg")
const TourismPath = require("../assets/Tourism.jpg")
const SportPath = require("../assets/Sport.jpg")
const FashionPath = require("../assets/Fashion.jpg")
const ClothesPath = require("../assets/Clothes.jpg")
const Clothes2Path = require("../assets/Clothes2.jpg")
const Fashion2Path = require("../assets/Fashion2.jpg")
const SummerPath = require("../assets/Summer.jpg")
const AutumnPath = require("../assets/Autumn.jpg")
const Clothes3Path = require("../assets/Clothes3.jpg")
const Summer2Path = require("../assets/Summer2.jpg")
const Summer3Path = require("../assets/Summer3.jpg")
const facebookPath = require("../assets/facebook-logo.jpg")
const pinterestPath = require("../assets/pinterest.jpg")
const vimeoPath = require("../assets/vimeo.jpg")
const dribbblePath = require("../assets/dribbble.jpg")
const twitterPath = require("../assets/twitter.jpg")
const behancePath = require("../assets/behance.jpg")
const instagramPath = require("../assets/instagram.jpg")
const youtubePath = require("../assets/youtube.jpg")
const googlePath = require("../assets/Google.jpg")
const KatePath = require("../assets/Kate.jpg")
const JeansPath = require("../assets/Jeans.jpg")
const CityPath = require("../assets/City.jpg")
const PhototgraphyPath = require("../assets/Phototgraphy.jpg")
const Woman1Path = require("../assets/Woman1.jpg")
const Woman2Path = require("../assets/Woman2.jpg")
const Woman3Path = require("../assets/Woman3.jpg")
const Woman4Path = require("../assets/Woman4.jpg")
const Woman5Path = require("../assets/Woman5.jpg")
const Woman6Path = require("../assets/Woman6.jpg")
const logo2Path = require("../assets/Logotype.jpg")
const linePath = require("../assets/Line.jpg")
const facebook2Path = require("../assets/facebook2.jpg")
const twitteractivePath = require("../assets/twitter_active.jpg")
const pinterest2Path = require("../assets/pinterest2.jpg")
const GooglePlay2Path = require("../assets/GooglePlay2.jpg")
const behance2Path = require("../assets/behance2.jpg")
const instagram2Path = require("../assets/instagram2.jpg")
const Logo = document.getElementById("logo")
const Logo2 = document.getElementById("logo2")
const line = document.getElementById("Line")
const facebook2 = document.getElementById("facebook2")
const twitteractive = document.getElementById("twitteractive")
const pinterest2 = document.getElementById("pinterest2")
const GooglePlay2 = document.getElementById("GooglePlay2")
const behance2 = document.getElementById("behance2")
const instagram2 = document.getElementById("instagram2")
line.src = linePath
facebook2.src = facebook2Path
Logo2.src = logo2Path
twitteractive.src = twitteractivePath
pinterest2.src = pinterest2Path
GooglePlay2.src = GooglePlay2Path
behance2.src = behance2Path
instagram2Path.src = instagram2
const Tourism = document.getElementById("Tourism")
const Sport = document.getElementById("Sport")
const Fashion = document.getElementById("Fashion")
const Clothes = document.getElementById("Clothes")
const Clothes2 = document.getElementById("Clothes2")
const Fashion2 = document.getElementById("Fashion2")
const Summer = document.getElementById("Summer")
const Autumn = document.getElementById("Autumn")
const Clothes3 = document.getElementById("Clothes3")
const Summer2 = document.getElementById("Summer2")
const Summer3 = document.getElementById("Summer3")
const facebook = document.getElementById("facebook-logo")
const pinterest = document.getElementById("pinterest")
const vimeo = document.getElementById("vimeo")
const dribbble = document.getElementById("dribbble")
const twitter = document.getElementById("twitter")
const behance = document.getElementById("behance")
const instagram = document.getElementById("instagram")
const youtube = document.getElementById("youtube")
const google = document.getElementById("google")
const Kate = document.getElementById("Kate")
const Jeans = document.getElementById("Jeans")
const City = document.getElementById("City")
const Phototgraphy = document.getElementById("Phototgraphy")
const Woman1 = document.getElementById('woman1')
const Woman2 = document.getElementById('woman2')
const Woman3 = document.getElementById('woman3')
const Woman4 = document.getElementById('woman4')
const Woman5 = document.getElementById('woman5')
const Woman6 = document.getElementById('woman5')
Logo.src = LogoPath
Tourism.src = TourismPath
Sport.src = SportPath
Fashion.src = FashionPath
Clothes.src = ClothesPath
Clothes2.src = Clothes2Path
Fashion2.src = Fashion2Path
Summer.src = SummerPath
Autumn.src = AutumnPath
Clothes3.src = Clothes3Path
Summer2.src = Summer2Path
Summer3.src = Summer3Path
facebook.src = facebookPath
pinterest.src = pinterestPath
vimeo.src = vimeoPath
dribbble.src = dribbblePath
twitter.src = twitterPath
behance.src = behancePath
instagram.src = instagramPath
youtube.src = youtubePath
google.src = googlePath
Kate.src = KatePath
Jeans.src = JeansPath
City.src = CityPath
Phototgraphy.src = PhototgraphyPath
Woman1.src = Woman1Path
Woman2.src = Woman2Path
Woman3.src = Woman3Path
Woman4.src = Woman4Path
Woman5.src = Woman5Path
Woman6.src = Woman6Path